### ISSUE TITLE
not applicable method for `lint_sentence_case` applied to `NULL` error

### ISSUE THREAD

**Issue by danielinteractive** [dgkf/roxylint#4]
When running the `roxylint` on a `package.R` file, e.g. https://github.com/Genentech/jmpost/blob/main/R/jmpost-package.R, then I get the error that a not applicable method for `lint_sentence_case` was applied to `NULL`.

I guess the linting of the title field (and others) should be made conditional on its presence maybe.

**Comment by dgkf** [comment]
_edit: accidentally posted in wrong thread, but I meant to respond here as well_

Thanks @danielinteractive. These functions underwent a bit of turnover as I refined the interface. We might need to specifically handle the NULL case still.

**Comment by dgkf** [comment]
Just investigating this further. This seems to be a special case when using the roxygen2 keyword `"_PACKAGE"`, which pulls a title and description from `DESCRIPTION` and doesn't have a "raw" doc string.

```
#' @keywords internal
"_PACKAGE"
```

So I think just handling this as a special case and avoiding reporting lints in this case is valid.
